filter:
  excluded_paths:
    - 'assets/*'
    - 'tests/*'
    - 'vendor/*'

tools:
  external_code_coverage:
    enabled: true
    timeout: 900
  php_analyzer: true
  php_code_coverage: true
  php_code_sniffer: true
  php_cpd: true
  php_cs_fixer: true
  php_loc: true
  php_mess_detector: true
  php_pdepend: true
  sensiolabs_security_checker: true

checks:
  php:
    verify_property_names: true
    verify_argument_usable_as_reference: true
    verify_access_scope_valid: true
    variable_existence: true
    useless_calls: true
    use_self_instead_of_fqcn: true
    use_statement_alias_conflict: true
    uppercase_constants: true
    unused_variables: true
    unused_properties: true
    unused_parameters: true
    unused_methods: true
    unreachable_code: true
    too_many_arguments: true
    symfony_request_injection: true
    switch_fallthrough_commented: true
    sql_injection_vulnerabilities: true
    single_namespace_per_use: true
    simplify_boolean_return: true
    side_effects_or_types: true
    return_in_constructor: true
    security_vulnerabilities: true
    return_doc_comments: true
    return_doc_comment_if_not_inferrable: true
    require_scope_for_properties: true
    require_scope_for_methods: true
    require_php_tag_first: true
    remove_extra_empty_lines: true
    psr2_switch_declaration: true
    psr2_class_declaration: true
    property_assignments: true
    precedence_in_conditions: true
    prefer_while_loop_over_for_loop: true
    precedence_mistakes: true
    phpunit_assertions: true
    php5_style_constructor: true
    parse_doc_comments: true
    parameter_non_unique: true
    parameter_doc_comments: true
    overriding_private_members: true
    param_doc_comment_if_not_inferrable: true
    optional_parameters_at_the_end: true
    overriding_parameter: true
    one_class_per_file: true
    no_underscore_prefix_in_properties: true
    no_unnecessary_final_modifier: true
    no_unnecessary_if: true
    no_underscore_prefix_in_methods: true
    no_trait_type_hints: true
    no_trailing_whitespace: true
    no_short_variable_names:
      minimum: ' 2'
    no_short_open_tag: true
    no_short_method_names:
      minimum: ' 3'
    no_property_on_interface: true
    no_non_implemented_abstract_methods: true
    no_long_variable_names:
      maximum: '20'
    no_goto: true
    no_global_keyword: true
    no_exit: true
    no_eval: true
    no_error_suppression: true
    no_empty_statements: true
    no_duplicate_arguments: true
    no_debug_code: true
    no_commented_out_code: true
    newline_at_end_of_file: true
    more_specific_types_in_doc_comments: true
    missing_arguments: true
    method_calls_on_non_object: true
    line_length:
      max_length: '120'
    instanceof_class_exists: true
    foreach_usable_as_reference: true
    foreach_traversable: true
    fix_use_statements:
      remove_unused: true
      preserve_multiple: false
      preserve_blanklines: false
      order_alphabetically: true
    fix_line_ending: true
    fix_doc_comments: true
    encourage_single_quotes: true
    encourage_shallow_comparison: true
    encourage_postdec_operator: true
    duplication: true
    deprecated_code_usage: true
    deadlock_detection_in_loops: true
    custom_coding_standard:
      ruleset_path: ruleset.xml
    comparison_always_same_result: true
    coding_standard:
      name: WordPress
    code_rating: true
    closure_use_not_conflicting: true
    closure_use_modifiable: true
    check_method_contracts:
      verify_interface_like_constraints: true
      verify_documented_constraints: true
      verify_parent_constraints: true
    catch_class_exists: true
    call_to_parent_method: true
    blank_line_after_namespace_declaration: true
    avoid_useless_overridden_methods: true
    avoid_usage_of_logical_operators: true
    avoid_unnecessary_concatenation: true
    avoid_superglobals: true
    avoid_perl_style_comments: true
    avoid_multiple_statements_on_same_line: true
    avoid_length_functions_in_loops: true
    avoid_entity_manager_injection: true
    avoid_duplicate_types: true
    avoid_corrupting_byteorder_marks: true
    avoid_conflicting_incrementers: true
    avoid_closing_tag: true
    avoid_aliased_php_functions: true
    assignment_of_null_return: true
    argument_type_checks: true
    align_assignments: true
