language: php

branches:
  only:
    - master
    - /^(?:(\d+)\.)?(?:(\d+)\.)?(\*|\d+)$/

services:
  - mysql

cache:
  apt: true
  yarn: true
  directories:
    - $HOME/.composer/cache/files

addons:
  apt:
    packages:
      - nginx
  hosts:
    - wp.dev

notifications:
  email:
    on_success: never
    on_failure: change

php:
  - 7.1
  - 7.2
  - nightly

env:
  global:
    - COMPOSER_NO_INTERACTION=1
  matrix:
    - WP_VERSION=nightly
    - WP_VERSION=latest WITH_COVERAGE=true
    - WP_VERSION=4.9.3
    - WP_VERSION=4.8.5

matrix:
  allow_failures:
    - php: nightly
    - env: WP_VERSION=nightly
  fast_finish: true

before_install:
  # Disable xDebug to speed up the build unless test coverage is needed
  - if [[ "$WITH_COVERAGE" != "true" ]]; then phpenv config-rm xdebug.ini; fi

  # Install helper scripts
  - travis_retry composer global require --prefer-dist --no-suggest typisttech/travis-nginx-wordpress:^3.0
  - export PATH=$HOME/.composer/vendor/bin:$PATH
  - tnw-install-nginx
  - tnw-install-wordpress
  - tnw-prepare-codeception

  # Build the production plugin
  - travis_retry composer build
  # Activate the plugin
  - wp plugin install ./release/wp-cloudflare-guard.zip --force --activate --path=/tmp/wordpress
  # Export a dump of plugin-activated database to the _data folder
  - wp db export $TRAVIS_BUILD_DIR/tests/_data/dump.sql --path=/tmp/wordpress

install:
  - travis_retry composer install --prefer-dist --no-suggest

script:
  - if [[ "$WITH_COVERAGE" == "true" ]]; then vendor/bin/codecept run --coverage --coverage-xml; fi
  - if [[ "$WITH_COVERAGE" != "true" ]]; then vendor/bin/codecept run; fi

after_script:
  - if [[ "$WITH_COVERAGE" == "true" ]]; then travis_retry tnw-upload-coverage-to-scrutinizer; fi
  - if [[ "$WITH_COVERAGE" == "true" ]]; then travis_retry tnw-upload-coverage-to-codecov; fi

before_deploy:
  - unzip -qo release/wp-cloudflare-guard.zip -d build

deploy:
  - provider: releases
    api_key: $GITHUB_ACCESS_TOKEN
    file: release/wp-cloudflare-guard.zip
    skip_cleanup: true
    on:
      condition: "$WP_VERSION = latest"
      php: 7.1
      tags: true
      repo: TypistTech/wp-cloudflare-guard
  - provider: wordpress-plugin
    edge:
      source: TypistTech/dpl
      branch: add-wordpress-plugin-deployment
    slug: wp-cloudflare-guard
    username: tangrufus
    build_dir: build
    assets_dir: assets
    skip_cleanup: true
    on:
      condition: "$WP_VERSION = latest"
      php: 7.1
      tags: true
      repo: TypistTech/wp-cloudflare-guard
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_ACCESS_TOKEN
    local_dir: build
    target_branch: nightly
    project_name: "WP Cloudflare Guard"
    on:
      branch: master
      condition: "$WP_VERSION = latest"
      php: 7.2
      repo: TypistTech/wp-cloudflare-guard
